/**
 * Site-wide constants. VERSION + release/asset URLs are generated by
 * `scripts/fetch-release.mjs` (see `lib/release.generated.ts`) so they are
 * never hardcoded — the build fetches the latest GitHub release.
 */
export {
	LATEST_VERSION,
	RELEASE_BASE,
	RELEASE_PAGE,
	ASSETS,
} from "@/lib/release.generated"

export const SITE_URL = "https://www.hoardodile.com"
export const SITE_NAME = "Hoardodile"
export const OG_IMAGE = "/og.png"
