import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const websiteRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const outFile = join(websiteRoot, "lib", "release.generated.ts")
const RELEASE_PAGE = "https://github.com/hoardodile/hoardodile/releases"
const RELEASE_BASE = `${RELEASE_PAGE}/latest/download`
const REPO_PKG = join(websiteRoot, "..", "hoardodile", "package.json")

function normalizeTag(tag) {
	return String(tag ?? "").replace(/^v/i, "").trim()
}

/** Prefer the authoritative `releases/latest`, fall back to the quota-free
    Atom feed, then the repo package.json version, then a constant. */
async function fetchReleaseVersion() {
	try {
		const res = await fetch(
			"https://api.github.com/repos/hoardodile/hoardodile/releases/latest",
			{ headers: { "User-Agent": "hoardodile-website" } },
		)
		if (res.ok) {
			const data = await res.json()
			const v = normalizeTag(data.tag_name)
			if (v) return v
		}
	} catch {}
	try {
		const res = await fetch("https://github.com/hoardodile/hoardodile/releases.atom")
		if (res.ok) {
			const body = await res.text()
			const m = body.match(/releases\/tag\/([^/<\s"]+)/)
			if (m) {
				const v = normalizeTag(m[1])
				if (v) return v
			}
		}
	} catch {}
	return undefined
}

function fallbackVersion() {
	try {
		if (existsSync(REPO_PKG)) {
			const pkg = JSON.parse(readFileSync(REPO_PKG, "utf8"))
			if (typeof pkg.version === "string" && pkg.version.length > 0) {
				return pkg.version
			}
		}
	} catch {}
	return "0.1.6"
}

const version = (await fetchReleaseVersion()) || fallbackVersion()

const content = `// AUTO-GENERATED by scripts/fetch-release.mjs — do not edit.
export const LATEST_VERSION = ${JSON.stringify(version)}
export const RELEASE_PAGE = ${JSON.stringify(RELEASE_PAGE)}
export const RELEASE_BASE = ${JSON.stringify(RELEASE_BASE)}
export const ASSETS = {
	winInstaller: \`\${RELEASE_BASE}/Hoardodile-Setup-\${LATEST_VERSION}-x64.exe\`,
	winPortable: \`\${RELEASE_BASE}/Hoardodile-\${LATEST_VERSION}-win-x64.zip\`,
	macDmg: \`\${RELEASE_BASE}/Hoardodile-\${LATEST_VERSION}-arm64.dmg\`,
	linuxAppImage: \`\${RELEASE_BASE}/Hoardodile-\${LATEST_VERSION}-x64.AppImage\`,
} as const
`

writeFileSync(outFile, content, "utf8")
console.log(`[fetch-release] LATEST_VERSION=${version} → ${outFile}`)
